version: '3'

services:
  web:
    restart: always
    image: python:3.10
    command: bash -c "pip install -r ./app/requirements.txt && python ./app/manage.py makemigrations && python ./app/manage.py migrate && python ./app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./restaurant_visit_diary:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=django_restaurants
      - DB_USER=postgres
      - DB_PASSWORD=django-restaurants
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=django-insecure-2#=2uska*^8#jt0@#%0u0tk3#v@y9@-8wio@7-una4=+irswhh
    networks:
      - your_network

  db:
    restart: always
    image: postgres:16
    environment:
      POSTGRES_DB: django_restaurants
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: django-restaurants
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - your_network

networks:
  your_network:
    driver: bridge

volumes:
  postgres_data: