version: '3'

services:
  web:
    restart: always
    image: python:3.10
    command: bash -c "pip install -r ./app/requirements.txt && python ./app/manage.py makemigrations && python ./app/manage.py migrate && python ./app/manage.py initadmin && python ./app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./restaurant_visit_diary:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - django_network

  db:
    restart: always
    image: postgres:16
    environment:
      POSTGRES_DB: django_restaurants
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: django-restaurants
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${EXTERNAL_DB_PORT}:5432"
    networks:
      - django_network

networks:
  django_network:
    driver: bridge

volumes:
  postgres_data: