version: '3'

services:
  web:
    restart: always
    container_name: "web_django"
    build:
      context: .
      dockerfile: django_dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis_db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - REDIS_HOST=redis_db
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT_TYPE=${ENVIRONMENT_TYPE}
    networks:
      - django_network

  celery:
    restart: always
    container_name: "celery_django"
    build:
      context: .
      dockerfile: django_celery_dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis_db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - REDIS_HOST=redis_db
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT_TYPE=${ENVIRONMENT_TYPE}
    networks:
      - django_network

  db:
    restart: always
    image: postgres:16
    container_name: "postgres_django"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${EXTERNAL_DB_PORT}:5432"
    networks:
      - django_network

  redis_db:
    restart: always
    image: "redis:latest"
    container_name: "redis_django"
    ports:
      - "${EXTERNAL_REDIS_PORT}:6379"
    networks:
      - django_network

networks:
  django_network:
    driver: bridge

volumes:
  postgres_data: