# Generated by Django 4.0.6 on 2024-01-14 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapiapp', '0002_restaurant_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='restaurantapiapp.restaurant'),
        ),
    ]
