name: Django CI

env:
    PYTHON_VERSION: '3.10'
    DB_NAME: django_restaurants
    DB_USER: postgres
    DB_PASSWORD: django-restaurants
    DB_HOST: localhost
    REDIS_HOST: localhost
    DB_PORT: 5432

on:
  push:
    branches: [ "master" ]
    
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: django_restaurants  
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: django-restaurants
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python ${{env.PYTHON_VERSION}}
      uses: actions/setup-python@v3
      with:
        python-version: ${{env.PYTHON_VERSION}}

    - run: pip install flake8
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Migrate
      run: |
        python ./restaurant_visit_diary/manage.py migrate
      env:
          DB_NAME: ${{env.DB_NAME}}
          DB_USER: ${{env.DB_USER}}
          DB_PASSWORD: ${{env.DB_PASSWORD}}
          DB_HOST: ${{env.DB_HOST}}
          DB_PORT: ${{env.DB_PORT}}
          REDIS_HOST: ${{ env.REDIS_HOST }}
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        
    - name: Run Tests
      run: |
        python ./restaurant_visit_diary/manage.py test restaurantapiapp
      env:
          DB_NAME: ${{env.DB_NAME}}
          DB_USER: ${{env.DB_USER}}
          DB_PASSWORD: ${{env.DB_PASSWORD}}
          DB_HOST: ${{env.DB_HOST}}
          DB_PORT: ${{env.DB_PORT}}
          REDIS_HOST: ${{ env.REDIS_HOST }}
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    - run: flake8 .
